import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Sagar's Space</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <nav className="flex items-center justify-between w-full px-4 py-16 backdrop-filter backdrop-blur">


          <div className="flex items-center gap-4">
            <img src="/sck.png" alt="logo" className="w-128 h-8 px-16" />
          </div>
          <div className="flex items-center gap-16 px-8">
            {/* Create a link to bring to the education section which is on the same page*/}
            <Link href="/#education" className="text-lg font-bold text-white hover:text-[#283044]">
              Education
            </Link>
            {/* Skills */}
            <Link href="/#skills" className="text-lg font-bold text-white hover:text-[#283044]">
              Skills
            </Link>
            {/* Experience */}
            <Link href="/#experience" className="text-lg font-bold text-white hover:text-[#283044]">
              Experience
            </Link>
            <Link href="/blog " className="text-lg font-bold text-white hover:text-[#283044]">
              Blog
            </Link>
          </div>
        </nav>

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            A Collection of my <span className="text-[hsl(280,100%,70%)]">Thoughts</span>
          </h1>

          {/* Entry 1 */}
          <div id="education" className="container flex flex-col items-center justify-center gap-16 px-4 py-16 bg-white/10  text-white rounded-2xl">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Entry 1
            </h1>
            {/* Create two columns (left for school right for university that have two rows withine ach of them the top row containing an image and the bottom containing a text description. */}
            <div className="grid grid-cols-1 gap-64 sm:grid-cols-2 md:gap-64">
              <div className="flex max-w-xs flex-col gap-4 rounded-2xl">
                {/* Add the image for school */}
                <img src="/varian.png" alt="logo" className="w-full h-full rounded-2xl" />
                <h1  className="text-lg font-bold text-white">
                Franconian International School
                </h1>
                <div className="text-lg">
                  I am a graduate of the FIS in 2022. I studied the International Baccalaureate Diploma Programme and graduated with a score of 43/45. I was also the recepient of the FIS Award in 2022.
                </div>
              </div>
              <div className="flex max-w-xs flex-col gap-4 rounded-2xl">
                {/* Add the image for school */}
                <img src="/tud.jpg" alt="logo" className="w-full h-full rounded-2xl" />
                <h1  className="text-lg font-bold text-white">
                  Delft University of Technology
                </h1>
                <div className="text-lg">
                  I am studying Computer Science and Engineering and am in my first year. I am part of Delft Aerospace Rocket Engineering (DARE) and am planning to do honours in the future.
                </div>
              </div>
            </div>
          </div>


          {/* Entry 2 */}
          <div id="education" className="container flex flex-col items-center justify-center gap-16 px-4 py-16 bg-white/10  text-white rounded-2xl">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Education
            </h1>
            {/* Create two columns (left for school right for university that have two rows withine ach of them the top row containing an image and the bottom containing a text description. */}
            <div className="grid grid-cols-1 gap-64 sm:grid-cols-2 md:gap-64">
              <div className="flex max-w-xs flex-col gap-4 rounded-2xl">
                {/* Add the image for school */}
                <img src="/fis.jpg" alt="logo" className="w-full h-full rounded-2xl" />
                <h1  className="text-lg font-bold text-white">
                Franconian International School
                </h1>
                <div className="text-lg">
                  I am a graduate of the FIS in 2022. I studied the International Baccalaureate Diploma Programme and graduated with a score of 43/45. I was also the recepient of the FIS Award in 2022.
                </div>
              </div>
              <div className="flex max-w-xs flex-col gap-4 rounded-2xl">
                {/* Add the image for school */}
                <img src="/tud.jpg" alt="logo" className="w-full h-full rounded-2xl" />
                <h1  className="text-lg font-bold text-white">
                  Delft University of Technology
                </h1>
                <div className="text-lg">
                  I am studying Computer Science and Engineering and am in my first year. I am part of Delft Aerospace Rocket Engineering (DARE) and am planning to do honours in the future.
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
